#!/bin/bash
echo "[DOIT] Welcome to the quicker docker builder for docker-react-dungeons-dragons-dice-roller website running on localhost!"
echo "   b to build the docker image, or"
echo "   r to run a docker container, or"
echo "   m to run and also map the container's /mnt folder to host's $PWD for dev purposes, or"
echo "   q to quit, "
read -p " and hit enter: " rc
case "$rc" in
	b)  docker build -t docker-react-dungeons-dragons-dice-roller .;;
        r)  echo "Running a docker container (no /mnt)"
		docker run -td -p 80:3000 docker-react-dungeons-dragons-dice-roller;;
        m)  echo "Running the docker container (with /mnt for dev)"
		docker run -td -p 80:3000 -v $PWD:/mnt docker-react-dungeons-dragons-dice-roller;;
        q) exit;;
esac
./doit
